"""Initial migration

Revision ID: bf22438c2f29
Revises: 
Create Date: 2025-06-23 14:50:46.478302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf22438c2f29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('words_per_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('eng_learned_words', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('eng_skipped_words', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('last_learning_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'last_learning_date')
    op.drop_column('users', 'eng_skipped_words')
    op.drop_column('users', 'eng_learned_words')
    op.drop_column('users', 'words_per_day')
    # ### end Alembic commands ###
